### ISSUE TITLE
Use other colors

### ISSUE THREAD

**Issue by DutchPete** [isaacfreeman/kakano-obsidian-theme#2]
At present I am using the 1st color

![image](https://github.com/isaacfreeman/kakano-obsidian-theme/assets/10794265/7a51fa99-63f3-40b3-87a6-54c2d307be99)

How can I use the 2nd - 6th colors? I have not found a way to change color.
Nice theme, BTW.

**Comment by isaacfreeman** [comment]
Hi @DutchPete!

These colors are 1-6 colors aren't currently supported by Kakano. You should see another section in Style Settings below this titled **Kakano** where you can set the base color. THe section you've screenshotted is provided by the plugin `THeme Design Utilities`, which many users won't have installed.

Obsidian has some specific color names `color-red`, `color-orange` etc. that it uses in a few places in the UI (e.g. `color-red` is used for warning messages). Kakano sets these fromt he base color, with the hue shifted. So if you set a pale blue base color, you'll get a pale red for `color-red`.

That said, I do intend to look into these 1-6 colors. The fact that `Theme Design Utilities` shows settings for them suggests that they must be used somewhere, so perhaps I've missed their significance! Let me know if you have an idea how they're used, otherwise I'll see what I can work out.

**Comment by DutchPete** [comment]
Thanks for your feedback, Isaac.
I had noticed in the Style Settings that one can change the base color, however I did not do so because I cannot relate the base color to the color output of the theme:

![image](https://github.com/isaacfreeman/kakano-obsidian-theme/assets/10794265/aa8e5fe3-d47b-45c0-9f82-f5a7fb89581b)

So, if I would want to have the green color, what should I set as a base color? Green, of course, but which one specifically of the 100s of possibilities?

OK, you are going to look into it. The easiest for the user would be to just click on one the 6 options of output colors you give, and it's done.

**Comment by isaacfreeman** [comment]
I think there's a misunderstanding here, but I'm not sure where it is. I'll run over some context. I expect some of this will be obvious to you, so apologies for that, but hopefully there'll be something in here that wasn't obvious and clarifies the situation.

- The `Style Settings` plugin isn't made by me. It's widely used by many themes as a standard way to add settings. I link to it in the README file for Kakano, but they're separate projects.
- `Style Settings` has a section for each theme of plugin that uses it. All the settings provided by Kakano are under the `Kakano` section.
- The color settings you show in your first screenshot under the heading `Theme Design Utilities: Color Playground` aren't from Kakano, they're from the community plugin `Theme Design Utilities`. This is also not by me. It's a little unusual for a plugin to put stuff in Style Settings – that's normally just for themes – but it does, adding those "First Color", "Second Color" etc. settings.
- I looked into why `Theme Design Utilities` adds these settings. It looks like it's just a demo for theme developers showing how you can add new color settings to a theme. It's referenced [here](https://github.com/chrisgrieser/obsidian-theme-design-utilities/blob/main/README.md#markdown-note-display-your-current-theme-colors).
- I'm guessing that you may have installed `Theme Design Utilities` first, then `Kakano`, then `Style Settings`. If I have that right, you would have first seen the settings for `Theme Design Utilities` and `Kakano` at the same time, and it would have looked like all those settings came from Kakano.
- If you install and use another theme that uses `Style Settings` (e.g. `Minimal`) you should see something similar. When Minimal is active its settings will replace Kakano's, but the section `Theme Design Utilities: Color Playground` will still be there.

So, the upshot is that you're seeing some demo settings ("First Color", "Second Color" etc.) from `Theme Design Utilities` that don't do anything in Kakano. Only the `Base Color` setting is used by Kakano.

Regardless of that confusion, I'm taking a couple of points from your second comment. The screenshot there was really useful.

1. When you use the color selector for `Base color`, it's not obvious why it shows blue but the theme still uses purple. The short answer here is that you need to click `Save` before it knows to use blue. I'll have a think about how to make that clearer.
The slightly longer answer is that I wanted the theme background to work whether or not you install `Style Settings`. If you don't have it installed, then the base color for Kakano comes from the `Accent color` setting (which is purple by default). After `Style Settings` is installed it'll use the `Base color` instead, but it needs a click on `Save` before it registers.

2. You've suggested having a selection of example colors to choose from, which I like! I don't think `Style Settings` can support this exactly the way you envisage, but it should be possible to provide a drop-down selector to select from. This would help people get started without having to know to click on `Save`. I'll add this to my to-do list.

Sorry this is so long, but I hope it's cleared things up a bit.

**Comment by DutchPete** [comment]
Hi Isaac, many thanks for your reply.

I know the Style Settings is not made by you, it is made by Matthew Myers.
I realize that the Theme Design Utilities aren't yours, they are made by pseudometa, iirc. What threw me, however, was that it shows 6 colors, and Kakano also mentions 6 colors. Silly me to put 1+1 together to arrive at 3 — my apologies.

Moving on, I think it would be a big step forward to have the (potential) confusion about base color and rendered color resolved.

Another suggestion, though you might not agree: at present the background of the main pane is white (in Light mode), but would it not be nicer to make that lighter shade of the surrounding color such as mauve? Ditto for the other colors.

Anyway, kudos for a beautiful theme.

**Comment by isaacfreeman** [comment]
> What threw me, however, was that it shows 6 colors, and Kakano also mentions 6 colors. Silly me to put 1+1 together to arrive at 3 — my apologies.

Not at all! That's a useful insight regardless of how we got to it. I'd meant the hero image to imply "you can use whatever color you like", but of course I've used six specific colors in a rainbow sequence and it does look like I chose those six specifically. So why not lean into that and make them a set of default options?

> Another suggestion, though you might not agree: at present the background of the main pane is white (in Light mode), but would it not be nicer to make that lighter shade of the surrounding color such as mauve? Ditto for the other colors.

I've considered this. To my eye it looks better in white, as one of my goals has been to draw a clear visual distinction between the user's content (neutral white background) and Obsidian's UI (colored background).

That said, I've already made a compromise on this principle for dark mode, where the "Near black" option does exactly what you say. I figure dark mode is mainly about being easy on the eye, and in a dark room the slightly reduced contrast was worth it. I think full white works better in light mode than full black does in dark mode, but I can see an argument for consistency! I'll add it to my to-do list to have another look at this, thanks.

> Anyway, kudos for a beautiful theme.

Thanks! I'm really enjoying working on it.

If I do end up using some of your suggestions, I'd like to give you a credit in the README. Should I link to your Github profile https://github.com/DutchPete, or is there some other URL you'd like?

**Comment by DutchPete** [comment]
Hi Isaac

> If I do end up using some of your suggestions, I'd like to give you a credit in the README.
No need for that. I enjoy your theme and I enjoyed our constructive discussion, my small contribution to your hard work 😀

**Comment by isaacfreeman** [comment]
I've made an update with some new preset colors, updated copy for the settings, and an off-white option for light mode.

<img width="825" alt="Screenshot 2024-01-28 at 20 48 21" src="https://github.com/isaacfreeman/kakano-obsidian-theme/assets/342659/6e495ad4-0bcd-4caf-b479-8d3ba3c707dd">
