### ISSUE TITLE
Audio recorder "works" but the indicator of whether it is working or not seems to be hidden.

### ISSUE THREAD

**Issue by WinnerWind** [isaacfreeman/kakano-obsidian-theme#3]
When using the Audio Recorder core plugin, there is an indicator in the side bar as to whether it is being recorded or not.
![image](https://github.com/isaacfreeman/kakano-obsidian-theme/assets/71366717/687d23af-e4d2-4c07-b414-6abb2ccb1876)
Though minor, it seems that regardless of the vault used, at least in my testing, Kakano does not respond to this change in the icon, and hence it is never clear whether the audio recorder plugin is recording or not (Though, this is also a fault for the developers of this core plugin). 
https://youtu.be/nD6LHQSrqzY

Is this an issue that can be fixed? The small visual change in icon really makes it clear that the plugin is working or not. Alternatively Kakano could use it's own indicator (Like a full screen popup, or a big red ball near the bottom of the writing area), though, I am not a theme developer, and I do not know to what extent this is possible. 
Sorry for bringing this up!

**Comment by isaacfreeman** [comment]
Thank you, that's definitely a bug in Kakano.

There's supposed to be a standard appearance for that type of control when it's "active", and I've accidentally overridden it in the ribbon sidebar. Not many of the controls there use it, but Audio Recorder does. So I'll fix that.

I also agree that just being generically "active" doesn't seem like enough for Audio Recorder. Most other "active" things could be toggle don or off when you feel like it, but it's particularly important that you keep track of whether your mic is on or not. I'll think about how to give it some extra visual weight.

**Comment by isaacfreeman** [comment]
I've deployed an update that fixes the problem, and adds a pulsating red animation to the button so it's hard to forget when you're recording.

**Comment by WinnerWind** [comment]
Thank you for really paying attention to the community! Its really hard to find developers like you!
The pulsating animation is super helpful, and really more than I asked for!
Thank you!

**Comment by isaacfreeman** [comment]
> Thank you for really paying attention to the community! Its really hard to find developers like you!

Thank you. Likewise, I really appreciate getting bug reports. Obsidian is such a flexible tool that different users use very different sets of features. For my part I never use audio recording – the way my brain works, I find it easier to express myself directly in text. But I want Kakano to be a theme that works for most users, not just for me, so it's especially valuable to get feedback on features I don't use much myself.

In defence of other developers... people's lives are busy and it's hard to maintain time for an open source project, especially if it gets popular. I happen to have a window right now where my enthusiasm for working on Kakano is high, the number of bug reports to deal with is still relatively low, and I'm currently unemployed. I can't guarantee this much attention forever, it's just how things are aligned at the moment. Until I can find a new job, I'm enjoying doing software development the way I think it should be done!

> The pulsating animation is super helpful, and really more than I asked for!

Glad you like it. At some point I want to think some more about the exact colors it uses, as I think it looks off with some base colors. But everything can be improved somehow!
