### ISSUE TITLE
Context menus are broken in dark theme.

### ISSUE THREAD

**Issue by WinnerWind** [isaacfreeman/kakano-obsidian-theme#4]
This is an issue with all my vaults which are running the latest version of Kakano (Since 2.8.5 if I believe. It used to only happen in one vault but now it is an issue with every updated vault.)
Every context menu that pops up in Obsidian uses a white background regardless of the theme applied, but the text does not adapt to match the white background, but seems to follow the dark theme setting.
Here's a sandbox vault with Obsidian v1.5.3 running Kakano 2.9.1
![image](https://github.com/isaacfreeman/kakano-obsidian-theme/assets/71366717/e4e76280-f584-47e0-ad0e-a3ac471b058f)
Here's my other vaults on the same obsidian version, between versions Kakano 2.9.1 and 2.9.0
![image](https://github.com/isaacfreeman/kakano-obsidian-theme/assets/71366717/3968861f-12b3-44bc-83b8-da8309062cb7)
![image](https://github.com/isaacfreeman/kakano-obsidian-theme/assets/71366717/f7960e2b-ec40-4fb0-bb24-26f34e412099)
This is not an issue on Obsidian v1.5.3 running Kakano 2.7.2. I am not sure when exactly this bug came into play, but it seems to be very recent.
![image](https://github.com/isaacfreeman/kakano-obsidian-theme/assets/71366717/5ab79b7c-caf8-493b-a91b-ddb95a5d5c06)

Resetting style settings did not fix the issue. Dark mode note background setting does not affect the appearance of this bug.
Sorry for making so many bug reports!

Edit : Forgot to mention, but this affects the Right Click menu too. 
![image](https://github.com/isaacfreeman/kakano-obsidian-theme/assets/71366717/061b9010-9fab-4fb1-9b51-bfef11071a1d)
![image](https://github.com/isaacfreeman/kakano-obsidian-theme/assets/71366717/92bbf734-8035-4b4c-afb6-f371a7c4e1bc)

**Comment by isaacfreeman** [comment]
Great screenshots, thanks. I spotted this problem myself yesterday – I personally use native OS menus, but I deployed an update recently to style these menus for other users (they're used on desktop if your setting is non-native, but also in places on mobile whatever your settings). I forgot to check how they look in dark mode!

**Comment by isaacfreeman** [comment]
OK, you should have version 2.9.2 available now, which fixes this.
