### ISSUE TITLE
Font color

### ISSUE THREAD

**Issue by DutchPete** [isaacfreeman/kakano-obsidian-theme#5]
No issue, just sharing a thought.
I have only used Kahurangi and Karaka, and found this blue font color, `#000071`, to go very well with those 2 themes colors. A blue font color is reminiscent of blue ballpen ink.

**Comment by isaacfreeman** [comment]
Thanks! I've tried this out myself, and while it's not my personal preferred aesthetic, I can see what you mean. Especially with a more casual font it has a notebook look that I'm sure would work well for many people. Part of what I like about Obsidian's flexibility is that it allows people to relate to it in different ways, from a casual scrapbook to a Serious Tome of very important formal knowledge. I think I'm somewhere in between: I like to have Obsidian be the default place I record just about anything, including stupid jokes and nonsensical thoughts, but I also like to assign a more formal structure to parts of it.

Let me know if you can see ways that Kakano could be adjusted to fit your personal style of use. I've recently added an *Experimental* section to the settings to try out some new ideas.

**Comment by isaacfreeman** [comment]
Closing this issue for now, but I'm happy to open it again if there's more to discuss.

**Comment by DutchPete** [comment]
Thanks for your feedback.

> I like to have Obsidian be the default place I record just about anything, including stupid jokes and nonsensical thoughts, but I also like to assign a more formal structure to parts of it.

I am exactly the same. That is why I use the ballpen font color with a formal font, and I use a handwriting type for quotes only just to make them stand out a bit better.

> Let me know if you can see ways that Kakano could be adjusted to fit your personal style of use.

I think it is fine as they are. For personal style I use css snippets.
Thanks again for a beautiful theme.
